// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRXYr23e_5Wi-TjkDxxgjfMDc89XjMWOc',
    appId: '1:851284674363:web:619bdc6fbdeaa89edd591e',
    messagingSenderId: '851284674363',
    projectId: 'magritechapp',
    authDomain: 'magritechapp.firebaseapp.com',
    storageBucket: 'magritechapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLApj5Bogzxwk07Fos-PvwHqyJ6fsD4Zk',
    appId: '1:851284674363:android:0b74676262e645e7dd591e',
    messagingSenderId: '851284674363',
    projectId: 'magritechapp',
    storageBucket: 'magritechapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtl7E_t6WBwkEbR0svpDBwyGPyohTxbV0',
    appId: '1:851284674363:ios:3f2d0f85ef0cf121dd591e',
    messagingSenderId: '851284674363',
    projectId: 'magritechapp',
    storageBucket: 'magritechapp.appspot.com',
    iosClientId: '851284674363-gdommrvp6g3lj9ck13apni55i2c1901v.apps.googleusercontent.com',
    iosBundleId: 'com.example.eAgritechApp',
  );
}
